"""Manifest-backed offline synthetic data for conditioned Stage 2 training."""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from torch.utils.data import Dataset


REQUIRED_FIELDS = (
    "sample_id", "moving_path", "fixed_path", "flow_path",
    "valid_mask_path", "moving_id", "fixed_id",
)


def _resolve_inside(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    if not path.is_relative_to(root):
        raise ValueError(f"manifest path escapes dataset root: {relative}")
    return path


class OfflineStage2Dataset(Dataset):
    """Load deterministic cross-modal pairs generated by the offline builder.

    Images are stored as RGB PNG in display range and returned in the Stage 1
    range ``[-1, 1]``. Flow is a backward-sampling displacement ``(dy, dx)``
    in pixel units satisfying ``warp(moving, flow) ~= fixed`` geometrically.
    """

    def __init__(
        self, manifest: str | Path, root: str | Path, split: str | None = None,
        require_complete: bool = True,
    ) -> None:
        self.manifest = Path(manifest).expanduser().resolve()
        self.root = Path(root).expanduser().resolve()
        with self.manifest.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            missing = [
                field for field in REQUIRED_FIELDS
                if field not in (reader.fieldnames or [])
            ]
            if missing:
                raise ValueError(f"offline manifest is missing columns: {missing}")
            self.rows = [
                row for row in reader
                if split is None or not row.get("split") or row["split"] == split
            ]
        if not self.rows:
            raise RuntimeError(f"no offline Stage 2 samples selected from {self.manifest}")

        self.paths: list[dict[str, Path]] = []
        for row in self.rows:
            paths = {
                key: _resolve_inside(self.root, row[key])
                for key in (
                    "moving_path", "fixed_path", "flow_path", "valid_mask_path",
                )
            }
            if require_complete:
                missing_paths = [str(path) for path in paths.values() if not path.is_file()]
                if missing_paths:
                    raise FileNotFoundError(
                        f"offline sample {row['sample_id']} is incomplete: {missing_paths[0]}"
                    )
            self.paths.append(paths)

    @staticmethod
    def _image(path: Path) -> torch.Tensor:
        with Image.open(path) as image:
            array = np.asarray(image.convert("RGB"), dtype=np.float32) / 255.0
        array = np.ascontiguousarray(array.transpose(2, 0, 1))
        return torch.from_numpy(array).mul(2.0).sub(1.0)

    @staticmethod
    def _mask(path: Path) -> torch.Tensor:
        with Image.open(path) as image:
            array = np.asarray(image.convert("L"), dtype=np.uint8) > 0
        return torch.from_numpy(np.ascontiguousarray(array[None])).float()

    def __getitem__(self, index: int) -> dict[str, torch.Tensor | str]:
        row = self.rows[index]
        paths = self.paths[index]
        flow = np.load(paths["flow_path"], allow_pickle=False)
        if flow.ndim != 3 or flow.shape[0] != 2:
            raise ValueError(
                f"flow must have shape (2,H,W), got {flow.shape} at {paths['flow_path']}"
            )
        flow = torch.from_numpy(np.ascontiguousarray(flow.astype(np.float32)))
        moving = self._image(paths["moving_path"])
        fixed = self._image(paths["fixed_path"])
        mask = self._mask(paths["valid_mask_path"])
        if moving.shape != fixed.shape or flow.shape[1:] != moving.shape[1:]:
            raise ValueError(f"shape mismatch in offline sample {row['sample_id']}")
        if mask.shape[1:] != moving.shape[1:]:
            raise ValueError(f"mask shape mismatch in offline sample {row['sample_id']}")
        return {
            "moving": moving,
            "fixed": fixed,
            "flow": flow,
            "valid_mask": mask,
            "moving_id": torch.tensor(int(row["moving_id"]), dtype=torch.long),
            "fixed_id": torch.tensor(int(row["fixed_id"]), dtype=torch.long),
            "sample_id": row["sample_id"],
            "direction": row.get("direction", ""),
        }

    def __len__(self) -> int:
        return len(self.rows)
